// client-vue/component/scrollList/scrollList.vue
<template>
  <div class="scroll-list">
    <slot></slot>
    <div v-if="status === 'loading'" class="weui-loadmore">
      <i class="weui-loading"/>
      <span class="weui-loadmore__tips">正在加载</span>
    </div>

    <div v-if="hasMore === false" class="weui-loadmore weui-loadmore_line weui-loadmore_dot">
      <span class="weui-loadmore__tips"/>
    </div>

    <div v-if="status === 'empty'" class="weui-loadmore weui-loadmore_line">
      <span class="weui-loadmore__tips">暂无数据</span>
    </div>

  </div>
</template>

<script>
  export default {
    props: {
      scrollElement: {
        'default': null,
        required: false,
      },
      onLoad: {
        'default': ()=>{},
        required: false,
      },
      status: {
        'default': 'loading',
        required: false,
      },
      hasMore: {
        'default': false,
        required: true
      }
    },

    data () {
      return {
        isBindEvent: false,
      }
    },

    computed: {

    },

    methods: {
      bindEvent (e) { // 这里要用箭头函数
        let ele = e.target;
        let {scrollHeight, clientHeight, scrollTop} = ele;
        let extra = 20;

        if (scrollTop + clientHeight + extra >= scrollHeight && this.hasMore === true && this.status !== 'loading') {
          this.onLoad();
        }
      }
    },

    watch: {
      scrollElement (val, oldVal) {
        if (oldVal === null && val !== null && this.isBindEvent === false) {
          let ele = val;
          ele.addEventListener('scroll', this.bindEventBind, false);
          this.isBindEvent = true;
        }
      }
    },

    created () {
      this.bindEventBind = this.bindEvent.bind(this);
    },

    mounted () {
      if (this.scrollElement !== null && this.isBindEvent === false) {
        this.scrollElement.addEventListener('scroll', this.bindEvent, false);
        this.isBindEvent = true;
      }
    },
  }
</script>

<style>

</style>

// client-react/component/scrollList/scrollList.jsx
import './scrollList.less';
import React, { Component, Children } from 'react';
import { findDOMNode } from 'react-dom';
import PropTypes from 'prop-types';

export default class extends Component {
  constructor () {
    super();
    this.state = {
      isBindScrollEvent: false,
      status: 'init' // init wait
    };
    this.elementScrollHandlerBind = this.elementScrollHandler.bind(this);
  }

  static propTypes = {
    hasMore: PropTypes.bool, // 是否还有更多
    loading: PropTypes.bool, // 是否能够加载，请求中的状态不允许加载
    onLoad: PropTypes.func, // 加载的函数
    element: PropTypes.object, // 监听的元素
    extra: PropTypes.number, // 额外的底边距
    isEmpty: PropTypes.bool // 是否为空
  };

  static defaultProps = {
    hasMore: true,
    loading: true,
    onLoad: ()=>{},
    element: null,
    extra: 10
  };

  elementScrollHandler (e) {
    let { scrollHeight, clientHeight, scrollTop } = e.target;
    let { loading, onLoad, hasMore, extra } = this.props;

    console.log('loading:', loading, 'hasMore', hasMore);
    if ( clientHeight + scrollTop + extra >= scrollHeight && !loading && hasMore ) {
      onLoad();
    }
  }

  componentWillReceiveProps (nextProps) {
    this.tryToBindScrollEvent(nextProps.element);
  }

  componentDidMount () {
    this.tryToBindScrollEvent(this.props.element);
  }

  tryToBindScrollEvent (element) {
    let { isBindScrollEvent } = this.state;

    if ( element && isBindScrollEvent === false ) {
      element.addEventListener('scroll', this.elementScrollHandlerBind, false);
      this.setState({ isBindScrollEvent: true });
    }
  }

  componentWillUnmount () {
    let { element } = this.props;
    if ( element ) {
      element.removeEventListener('scroll', this.elementScrollHandlerBind, false);
    }
  }

  render () {
    let { loading, hasMore, isEmpty } = this.props;

    return (
      <div className="scroll-list">
        {this.props.children}
        {
          loading &&
            <div className="weui-loadmore">
              <i className="weui-loading"/>
              <span className="weui-loadmore__tips">正在加载</span>
            </div>
        }
        {
          !hasMore &&
            <div className="weui-loadmore weui-loadmore_line weui-loadmore_dot">
              <span className="weui-loadmore__tips"/>
            </div>
        }
        {
          isEmpty &&
            <div className="weui-loadmore weui-loadmore_line">
              <span className="weui-loadmore__tips">暂无数据</span>
            </div>
        }
      </div>
    );
  }
}
