// client/container/index/index.jsx
import './index.less';
import React, { Component } from 'react';
import { connect } from 'react-redux';
import actions from '../../redux/actions/index.js';
import { Link } from 'react-router-dom';
import ScrollList from '../../component/scrollList/scrollList.jsx';
import FeedCard from '../../component/feedCard/feedCard.jsx';

@connect((state) => {
  return {
    myInfo: state.myInfo,
    myListInfo: state.myListInfo,
    mainPage: state.mainPage
  }
},{...actions})
export default class extends Component {
  constructor () {
    super();
    this.state = {

    };
  }

  componentWillMount () {
    this.props.getMyInfo();
    this.props.getMyList();
  }

  componentDidMount () {
    // console.log(this.refs);
    // debugger
  }

  render () {
    let {
      myInfo: { userName, avatar, getupTime, rank, continued }
    } = this.props;

    let { list, hasMore, loading, isEmpty } = this.props.myListInfo;

    return (
        <div className="page-wrap main-page" ref="mainPage">
          <div className="my-avatar">
            <img src={avatar}/>
          </div>
          <div className="my-name">{userName}</div>
          <div className="get-up-wrap">
            <span>{getupTime}</span>
          </div>
          <Link to='/new'>
            <div className="new-wrap weui-cells">
                <span className="add-icon">+</span>
                <span className="add-text">添加今日状态</span>
            </div>
          </Link>
          <div className="weui-cells__title">最近七天</div>
          <ScrollList
            element={this.refs.mainPage}
            onLoad={this.props.getMyList}
            hasMore={hasMore}
            loading={loading}
            isEmpty={isEmpty}
          >
            <ul className="recently-wrap">
              {
                list.map((item, index) => {
                  return (
                    <FeedCard route="/detail/222" item={item} key={index}/>
                  )
                })
              }
            </ul>
          </ScrollList>
        </div>
    )
  }
}

// client-vue/container/index/index.vue
<template>
  <div class="index-page" ref="indexPage">
    <div class="user-info-wrap">
      <img class="avatar-img" :src="myInfo.avatar" :alt="myInfo.userName"/>
      <p class="user-name">{{myInfo.userName}}</p>
    </div>
    <div class="new-wrap weui-cells">
      <span class="add-icon">+</span>
      <span class="add-text">添加今日状态</span>
    </div>
    <div class="weui-cells__title">最近状态</div>
    <scroll-list
      :scrollElement="$refs.indexPage"
      :status="myList.status"
      :hasMore="myList.hasMore"
      :onLoad="this.getMyList"
    >
      <div>
        <feed-card v-for="(item, index) in myList.list" :key="index" :img="item.img" :text="item.text" :time="item.time"></feed-card>
      </div>
    </scroll-list>
  </div>
</template>
<script>
  import {mapGetters, mapActions, mapState} from 'vuex';
  import ScrollList from '../../component/scrollList/scrollList.vue';
  import FeedCard from '../../component/feedCard/feedCard.vue';

  export default {
    data() {
      return {}
    },

    components: {
      ScrollList, FeedCard
    },

    computed: {
      ...mapState({
        myInfo: state => state.main.myInfo,
        myList: state => state.main.myList,
      })
    },

    methods: {
      ...mapActions(['getMyInfo', 'getMyList']),
    },

    mounted () {

    },

    created() {
      this.getMyInfo();
      this.getMyList();
    },
  }
</script>

<style lang="less">
  .user-info-wrap {
    text-align: center;
    margin-top: 30px;
    .avatar-img {
      width: 100px;
      height: 100px;
      border-radius: 50%;
    }
    .user-name {
      font-size: 20px;
    }
  }

  .new-wrap {
    height: 70px;
    padding: 10px 10px 10px 20px;
    margin: 20px 0;
    .add-icon {
      font-size: 30px;
      font-weight: bold;
      margin-right: 10px;
    }
    .add-text {
      vertical-align: 2px;
    }
  }
</style>
